Import accel-pptp v0.8.3

diff --git a/README b/README
--- a/README
+++ b/README
@@ -61,6 +61,11 @@ Kernel module is available as separated module and as patch for kernel.
 You can use either separated module or patch for kernel.
 There is only patch for 2.6.18 kernel now. If you wish patch for other kernels please mail me.
 
+ppp_generic_smp
+---------------
+This driver is replacement of kernel's ppp_generic for better smp performance.
+It is disables by default, to enable you should uncomment "#obj-m      += ppp_generic_smp.o" in kernel/driver/Makefile.
+
 
 Thanks
 ------
@@ -71,3 +76,43 @@ http://accel-pptp.sourceforge.net/
 mail: xeb@mail.ru, xeb@linux.vsi.ru
 ICQ: 337258064
 Jabber: xeb@city.veganet.ru, xeb@linux.vsi.ru
+MDIR = extra
+
+KDIR ?= $(shell sh find_kernel_headers)
+
+obj-m      += pptp.o
+
+CURRENT = $(shell uname -r)
+
+
+ifndef MAKING_MODULES
+all: kernel_headers
+	make -C $(KDIR) SUBDIRS=$(PWD) modules
+endif
+
+ifneq (,$(findstring 2.4.,$(CURRENT)))
+install:
+	@if test ! -d /lib/modules/$(CURRENT)/extra; then \
+	    mkdir /lib/modules/$(CURRENT)/extra; \
+	fi; \
+	cp -v $(TARGET).o /lib/modules/$(CURRENT)/extra/$(TARGET).o && /sbin/depmod -a
+else
+install:	
+	make -C $(KDIR) SUBDIRS=$(PWD) modules_install
+endif
+
+kernel_headers:
+	@if test -z "$(KDIR)"; then \
+	    echo "kernel headers not found"; \
+	    exit 1; \
+	else \
+	    echo "using \"$(KDIR)\" kernel headers"; \
+	fi
+
+
+clean:
+	-rm -f *.o *.ko .*.cmd .*.flags *.mod.c
+
+ifneq (,$(findstring 2.4.,$(CURRENT)))
+include $(KDIR)/Rules.make
+endif
