Import ASUS-MERLIN_380.70 for pppd
Change-Id: If1910864d7e0342c2bd52a532e4a828f6179fa9c

diff --git a/pptpd-1.3.3/configure b/pptpd-1.3.3/configure
--- a/pptpd-1.3.3/configure
+++ b/pptpd-1.3.3/configure
@@ -6222,29 +6222,30 @@ CFLAGS="${CFLAGS} -I. -I${header}"
 kernel_headers=${header}
 
 
-{ echo "$as_me:$LINENO: checking for pppd" >&5
-echo $ECHO_N "checking for pppd... $ECHO_C" >&6; }
-pppd=`which pppd 2>&1`
-if test $? -eq 1; then
-	pppd=""
-	for path in /usr/sbin /usr/local/sbin /usr/bin /usr/local/bin /sbin; do
-		if test -x ${path}/pppd; then
-			pppd=${path}/pppd
-			break;
-		fi
-	done
-fi
+#{ echo "$as_me:$LINENO: checking for pppd" >&5
+#echo $ECHO_N "checking for pppd... $ECHO_C" >&6; }
+#pppd=`which pppd 2>&1`
+#if test $? -eq 1; then
+#	pppd=""
+#	for path in /usr/sbin /usr/local/sbin /usr/bin /usr/local/bin /sbin; do
+#		if test -x ${path}/pppd; then
+#			pppd=${path}/pppd
+#			break;
+#		fi
+#	done
+#fi
 
-if test -z "${pppd}"; then
-    { echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6; }
-    { { echo "$as_me:$LINENO: error: Could not find pppd" >&5
-echo "$as_me: error: Could not find pppd" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-pppd_ver=`${pppd} --version 2>&1 | grep version | sed 's/pppd version //'`
-{ echo "$as_me:$LINENO: result: $pppd ($pppd_ver)" >&5
-echo "${ECHO_T}$pppd ($pppd_ver)" >&6; }
+#if test -z "${pppd}"; then
+#    { echo "$as_me:$LINENO: result: not found" >&5
+#echo "${ECHO_T}not found" >&6; }
+#    { { echo "$as_me:$LINENO: error: Could not find pppd" >&5
+#echo "$as_me: error: Could not find pppd" >&2;}
+#   { (exit 1); exit 1; }; }
+#fi
+#pppd_ver=`${pppd} --version 2>&1 | grep version | sed 's/pppd version //'`
+#{ echo "$as_me:$LINENO: result: $pppd ($pppd_ver)" >&5
+#echo "${ECHO_T}$pppd ($pppd_ver)" >&6; }
+pppd_ver="2.4.5"
 cat >>confdefs.h <<_ACEOF
 #define PPPD_VERSION "${pppd_ver}"
 _ACEOF
